language: java
install: mvn install -Dgpg.skip=true
jdk:
- oraclejdk7
- oraclejdk8
notifications:
  slack:
    secure: IRPCjMJOm3eKC8PwjsAVUXyxTgv8zC4BQadOORV1BFBfoXLalq4XJmesi3dWkVVJTf35SgKuqBTFvfEsVFEXwto1/QykNyZH7pe29XXN2PiL/dBC9cy7/qqqsh8+fnzFZXJOCM825XqAR06sOq5Xvl83a8IrA7zm5ysmw4jURPE=
deploy:
  provider: releases
  api_key:
    secure: FF+u1PjxvALghNFZ8uLMjY6MbfURo2cNVRiz1oLz1oqDzBwcOiyfs4Lpagt0KQ0ffCgPUBaYqs8MurH5Xoy59MlRF8HCqMoVBq2zJ+D5rUxKFhddCDZVz66wTSI0xJ04hcT8T6cip/l7dewB4p3pQFqTXl01WCV4bkpl0r1atRA=
  file: target/placeholders-mustachifier-maven-plugin-0.5.jar
  on:
    repo: xebialabs-community/placeholders-mustachifier-maven-plugin
    tags: true
