language: java
install: mvn install -Dgpg.skip=true
jdk:
- oraclejdk7
- oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: EHE0gqqjLcICY7CPynUXGlb/Ig2sGuBpnm32lK/H+vX4vnMaH0w9cktB8xZIV1jkVJ1tJYAojEsNJUNIV2aKcLTVEKdYigpcvJZNg4c9tlK60Khli5hbAEf5CFxBaq7aUySkewQQ2QcAmGjBUle4iLyo+PPXiQKkjtmQUfqDVxM=
deploy:
  provider: releases
  api_key:
    secure: FF+u1PjxvALghNFZ8uLMjY6MbfURo2cNVRiz1oLz1oqDzBwcOiyfs4Lpagt0KQ0ffCgPUBaYqs8MurH5Xoy59MlRF8HCqMoVBq2zJ+D5rUxKFhddCDZVz66wTSI0xJ04hcT8T6cip/l7dewB4p3pQFqTXl01WCV4bkpl0r1atRA=
  file: target/placeholders-mustachifier-maven-plugin-0.5.jar
  on:
    repo: xebialabs-community/placeholders-mustachifier-maven-plugin
    tags: true
